### PR TITLE
Update ZSS library to 1.4.11

### PR DESCRIPTION
**Pull request by cdjackson**
Bump the Zigbee libraries to the latest version. This fixes a few bugs and adds support for newer versions of the Silabs firmware.

@kaikreuzer when you get a chance can you update the distro and merge this.  Thanks.

### CODE REVIEW

**Comment by Hedda** [comment]
Nice, thank you [cdjackson](https://github.com/cdjackson)!

> adds support for newer versions of the Silabs firmware

For reference, this pull request should add support for EZSP v9, EZSP v10, and EZSP v11 (EmberZNet Serial Protocol versions 9, 10, and 11) for Silicon Labs Ember NCP dongles as per this feature request-> https://github.com/zsmartsystems/com.zsmartsystems.zigbee/issues/1332

This in practice means that end-users could use newer firmware based on Silabs EmberZNet 7.0.x, Silabs EmberZNet 7.1.x, and Silabs EmberZNet 7.2.x (including future/upcoming bug-fix releases of Silabs EmberZNet 7.0, EmberZNet 7.1, and EmberZNet 7.2).

It should however be noted that updating to those newer firmware versions will not bring any new features or functions and end-users need to be aware that using a newer firmware version might not necessarily be as stable as older more mature Silabs bug-fix releases of EmberZNet 6.7.x, Silabs EmberZNet 6.9.x, and Silabs EmberZNet 6.10.x firmware versions which are known to work well. 

So while it is great to see the proverb "if it ain't broke, don't fix it" certainly applies here. It is therefore generally recommended to not upgrade firmware just yet if you already have an existing Zigbee Coordinator dongle that is working well with openHAB ZigBee Binding. At least users do not have to downgrade firmware if happen to buy a new dongle that ship with newer firmware.

**Comment by cdjackson** [comment]
> For reference, this pull request should bring support for EZSP v9, EZSP v10, and EZSP v11 (new EmberZNet Serial Protocol versions 9, 10, and 11) for Silicon Labs Ember NCP dongles as per this feature request-> https://github.com/zsmartsystems/com.zsmartsystems.zigbee/issues/1332

To be clear the changes in EZSP version is only one of many changes, upgrades and bug fixes that this PR brings - it's not the only change.

**Comment by kaikreuzer** [comment]
@cdjackson I've uploaded the new versions to Artifactory.

**Comment by cdjackson** [comment]
Thanks Kai. Sent from my iPhoneOn 29 Apr 2023, at 21:33, Kai Kreuzer ***@***.***> wrote:﻿
Merged #804 into main.

**Pull request merged**
