### PR TITLE
Create new ZSS transport and config on handler restart

### PR DESCRIPTION
**Pull request by triller-telekom**
Relates to #474

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks for this @triller-telekom. 

IMHO this needs a little additional refactoring. With this PR, ```initialize``` and ```reinitialiseZigBee``` do the same thing - they are duplicated (except in the case of the XBee where the ```reinitialiseZigBee``` is empty so presumably won't work!).

I would suggest that instead of overloading the ```initialize``` method in each dongle which calls ```super.initialize```, you should instead remove the ```initialize``` method which now seems to only calls ```createDongle```, and just call ```reinitialiseZigBee``` from ```ZigBeeCoordinatorHandler.initialize()```.

This would simplify things and avoid duplication. WDYT?

**Comment by cdjackson** [comment]
@triller-telekom any progress on this?

**Comment by triller-telekom** [comment]
Hi Chris,

sorry that I haven't updated this PR since a while and that I am also replying late. Unfortunately I am very busy with other stuff at the moment, which is why I haven't updated this PR.

If you like to take over feel free, otherwise I can have a look once I find some time. Sorry.

**Comment by cdjackson** [comment]
Hi Stefan,
Ok, it’s no problem for me - I think you guys probably have more need to resolve this issue than me at the moment :)

Cheers
Chris

**Comment by cdjackson** [comment]
Replaced by #564

**Pull request closed without merging**
