### PR TITLE
Update Z-Smart Systems ZigBee library to 1.3.10

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Review by kaikreuzer — APPROVED** [review]

**Comment by kaikreuzer** [comment]
@cdjackson Same here: This change was merged to the 2.5.x branch, not against master, while openhab/openhab-distro#1201 clearly was for 3.0, hence I tagged the PR accordingly for 3.0 M5 and had it included in the release notes.
Why is the master branch not maintained on this repo?

**Comment by cdjackson** [comment]
This was added to 2.5 as users using 2.5 required these changes. I had intended to cherry pick across, but lost 2 servers last week and have unfortunately been spending time since rebuilding and recovering the data. So it is not that the master is not maintained, but simply that we have 2 versions that need to be maintained, and I did 2.5 first.

**Comment by kaikreuzer** [comment]
Thanks for the update! Sad to hear that you had such a severe IT issue, I wish you the best to get it all fully recovered again!

Please note that since September (and [this post](https://github.com/openhab/openhab-addons/issues/8512)), we have the policy that PRs should always go first to master and then being backported to 2.5.x if applicable (see point 2). The idea was to definitely make sure that the latest openHAB version also includes the latest fixes and that those are not forgotten.
This process should ideally also apply to Zigbee and Z-Wave, but I guess that this will come anyhow naturally with 3.0 being released soon (and hardly any further builds happening for 2.5).

**Comment by cdjackson** [comment]
Unfortunately I’ve have a strong need to support 2.5, so I’ve been trying to get updates into 2.5 and then cherry pick across - there haven’t been very many though. Sorry, but things have been quite busy for me in the last couple of months and I’ve had very limited time recently.

**Comment by kaikreuzer** [comment]
No need to apologize for anything, really! Just please help to ensure that we don't release 3.0 with broken/outdated Z-bindings, which would really be a shame!

**Comment by kaikreuzer** [comment]
@cdjackson I just noticed that this is still missing in master, but I have already triggered the RC2 build, which is supposed to be the final one for testing. Can you confirm that 1.3.10 does not contain any relevant fixes and we are fine to ship 3.0 with the 1.3.8 version?

**Comment by cdjackson** [comment]
Sorry Kai - I’m currently in the process of moving house (and country) so I really have limited time right now. The current version of the library is fine - there are no major changes in the latter version and we can introduce it later. Again - I’m sorry not to be able to support as much as needed at the moment.

**Comment by kaikreuzer** [comment]
Ok, Chris, thanks for the info and sorry for bothering you. Glad to hear that we can use the current version, so let's leave the upgrade for 3.1.

**Pull request merged**
