### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by cdjackson**
Signed-off-by: Chris Jackson <chris@cd-jackson.com>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hey @cdjackson, I added a commit to your branch/PR, which will make the tests run smoothly in the IDE - should be good to be merged.

**Comment by cdjackson** [comment]
Thanks @kaikreuzer - much appreciated :)
I'll give it a try later.

**Comment by cdjackson** [comment]
Thanks @kaikreuzer - it works.

**Comment by kaikreuzer** [comment]
Glad to hear that!

**Pull request merged**
