### PR TITLE
Added spotless config, see openhab-core issue 935

### PR DESCRIPTION
**Pull request by seime**
See https://github.com/openhab/openhab-core/issues/935

Signed-off-by: Arne Seime <arne.seime@gmail.com>

### CODE REVIEW

**Comment by seime** [comment]
Depends on https://github.com/openhab/openhab-core/pull/1101

**Comment by kaikreuzer** [comment]
@cdjackson Don't be too quick: @seime said it depends on https://github.com/openhab/openhab-core/pull/1101...

**Comment by kaikreuzer** [comment]
FTR, this currently makes our release build fail, see https://ci.openhab.org/view/Sandbox/job/sandbox-openhab2-release/.

**Comment by kaikreuzer** [comment]
As openhab/openhab-core#1101 can still take a while, I have reverted this PR with https://github.com/openhab/org.openhab.binding.zigbee/pull/511 for the moment.

**Pull request merged**
