### PR TITLE
add support for xiaomi wireless mini switch

### PR DESCRIPTION
**Pull request by t-8ch**
https://www.aqara.com/en/wireless_mini_switch.html

shortpress requires https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/556
doublepress requires support for proprietary attributes.

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks @t-8ch can I also ask you to add this to the list of supported devices in the readme?

**Comment by t-8ch** [comment]
I added the docs

**Comment by t-8ch** [comment]
There seem to be some more xiaomi devices in `discovery.txt` that I personally have no experience with,
I added all that I have personally seen working.

**Comment by cdjackson** [comment]
Thanks.

**Comment by JackBradRPI** [comment]
Hi Both,

I have a couple xiaomi mini switches (https://www.aqara.com/en/wireless_mini_switch.html).

I can add them using the zigbee binding, however they show an error message and dont show a channel (HANDLER_INITIALIZING_ERROR No supported clusters found)

Am i doing something wrong or are these not supported?

Thank you for your efforts

**Comment by t-8ch** [comment]
@JackBradRPI Unfortunately I don't have access to my openhab setup in the near future to doublecheck.

**Comment by JackBradRPI** [comment]
@t-8ch no problem, thank you for your quick reply. I have spent the past couple days reading up on the topic but I'm stuck! Will happily buy someone a beer to get it going :)

**Pull request merged**
