### PR TITLE
Adapted repo references to super pom

### PR DESCRIPTION
**Pull request by kaikreuzer**
See https://github.com/openhab/org.openhab.binding.zigbee/pull/454#issuecomment-516013624

Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by cdjackson** [comment]
Somehow my comment here got lost.

Regarding your comment -:

> we only use repos that are defined in the central super pom

I'm trying to understand why we can't define repositories in binding poms? This seems to be limiting - is there really a need to restrict this and only allow the master openhab pom to define where we get the bundles from? 

For example, is this needed somewhere when the bundles are resolved for the runtime?

**Comment by kaikreuzer** [comment]
Any repo other than Maven Central might disappear in future, making builds not reproducible.
That was the whole reason to introduce the super pom. With that, it is possible to adapt the repo locations retrospectively for OLD release versions as well. And no, there is not restricting flexibility as we can still add whatever repos we like to the virtual openHAB repo.

**Comment by cdjackson** [comment]
@kaikreuzer this PR does not build due to issues resolving parent pom.

```
13:50:54 Parsing POMs
13:50:55 ERROR: Failed to parse POMs
13:50:55 org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
13:50:55 [FATAL] Non-resolvable parent POM for org.openhab.addons.bundles:org.openhab.addons.zigbee.reactor:2.5.0-SNAPSHOT: Could not find artifact org.openhab.addons:org.openhab.addons.reactor:pom:2.5.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 6, column 11
13:50:55 
13:50:55 	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:383)
13:50:55 	at org.jfrog.build.extractor.maven.ArtifactoryProjectBuilder.build(ArtifactoryProjectBuilder.java:34)
13:50:55 	at hudson.maven.MavenEmbedder.buildProjects(MavenEmbedder.java:370)
13:50:55 	at hudson.maven.MavenEmbedder.readProjects(MavenEmbedder.java:340)
13:50:55 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1329)
13:50:55 	at hudson.maven.MavenModuleSetBuild$PomParser.invoke(MavenModuleSetBuild.java:1126)
13:50:55 	at hudson.FilePath.act(FilePath.java:1075)
13:50:55 	at hudson.FilePath.act(FilePath.java:1058)
13:50:55 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.parsePoms(MavenModuleSetBuild.java:987)
13:50:55 	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:691)
13:50:55 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
13:50:55 	at hudson.model.Run.execute(Run.java:1816)
13:50:55 	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
13:50:55 	at hudson.model.ResourceController.execute(ResourceController.java:97)
13:50:55 	at hudson.model.Executor.run(Executor.java:429)
13:50:55 Finished: FAILURE
```

**Comment by kaikreuzer** [comment]
Do you have any idea why? The parent pom clearly exists in https://ci.openhab.org/artifactory/libs-snapshot/org/openhab/addons/org.openhab.addons.reactor/2.5.0-SNAPSHOT/ and the build job is configured to resolve artifacts from there...?

**Comment by cdjackson** [comment]
No - I’ve not looked into this locally - only that CI doesn’t work any more and the error I posted is from the Jenkins build.

**Pull request closed without merging**
