### PR TITLE
Changed reporting default value for changes in Temperature and Humidity

### PR DESCRIPTION
**Pull request by FranzSchi**
Changed reporting default value for changes in Temperature and Humidity (Temperature is now 0.1 ° and Humidity 0,5%)

Signed-off-by: FranzSchi <Franz.Schindler@web.de>

### CODE REVIEW

**Comment by cdjackson** [comment]
Please can you update so this is only the humidity - I've already fixed all the temperature reports (I think?).

**Comment by FranzSchi** [comment]
> Please can you update so this is only the humidity - I've already fixed all the temperature reports (I think?).

Thanks Chris, I've just seen that you've commit it 1 min ago :-)

**Comment by cdjackson** [comment]
Yes, I went through and made the PR this morning, but just merged as I came home. There were a number of temperature reports and hopefully I've got them all.

There are no doubt other such errors (such as the humidity) so please feel free to provide a PR - it's much appreciated :)

**Comment by FranzSchi** [comment]
Thanks Chris, All right, I'll do so

**Pull request closed without merging**
