### PR TITLE
adapted code to match latest ESH APIs

### PR DESCRIPTION
**Pull request by kaikreuzer**
Signed-off-by: Kai Kreuzer <kai@openhab.org>

### CODE REVIEW

**Comment by kaikreuzer** [comment]
Hey @cdjackson - I am aware that you will push a huge update any time soon, but as I am preparing the inclusion of this binding in the official build, please allow me small fixes for issues that block me from doing so.

**Comment by cdjackson** [comment]
@kaikreuzer if you don't mind I will revert this as this has been completely rewritten and this will now cause conflicts? Is that ok?

**Comment by kaikreuzer** [comment]
Why should you revert it? If your new version does not include that part, it is absolutely fine. All I wanted to achieve is that the CURRENT version in the repo is at least buildable, so it should not be reverted.

**Comment by cdjackson** [comment]
Ok, I expect it to cause conflicts which I will need to resolve as all this is completely changed now.

**Comment by kaikreuzer** [comment]
No worries, just resolve any conflict in the code by choosing YOUR version - just make sure that the result builds nicely :-)

**Pull request merged**
