### PR TITLE
Make maven run the unit tests

### LINKED ISSUE #144: Unit tests not run by maven (as testSourceDirectory incorrectly configured)
In the `pom.xml`, the source directory for the tests is configured as `<testSourceDirectory>src/test</testSourceDirectory>`, although the unit tests are actually in directory `src/main/test`. In consequence, the maven build will not run any unit tests.

Besides that, would it be sensible to move the unit tests to `/src/test/java`, to align with default maven directory layout?

### PR DESCRIPTION
**Pull request by hsudbrock**
Fixes #144

Moves the unit tests from directory `src/main/test` to directory `src/test/java`, to adhere to the default maven directory structure, and removes `testSourceDirectory` directive from the `pom.xml`. In consequence, the unit tests are executed by the maven surefire plugin (whereas, before this change, surefire ran but could not find the tests).

Moreover, adds a small fix to the `ZigBeeConverterSwitchOnOffTest`, where mockito needs to be told explicitly the type for an 'any' matcher.

### CODE REVIEW

**Comment by cdjackson** [comment]
Thanks for this. I guess it was missed as tests were broken until recently due to mockito issues.
Please in future can you sign commits / PRs (thanks ;) ).

**Comment by hsudbrock** [comment]
@cdjackson Thanks for the hint regarding signing. Just to avoid that I misunderstand you: You are not talking about "signing off", but (in addition to signing off) about cryptographically signing (as detailed here: https://help.github.com/articles/signing-commits-with-gpg/), correct?

**Comment by cdjackson** [comment]
No - just the ```signed-off-by``` tag - as per the [contribution guidelines in OH](https://docs.openhab.org/developers/contributing/contributing#sign-your-work) (and I think it's exactly the same for ESH).

Thanks.

**Comment by kaikreuzer** [comment]
I would claim he did just that: https://github.com/openhab/org.openhab.binding.zigbee/pull/145/commits/9b9c4cf9a81022645fd82b4059b9992670f5170f

**Comment by cdjackson** [comment]
Ok, sorry - I thought the guidelines were to sign PRs as well, but it seems that's not required now that I read it again...

**Comment by hsudbrock** [comment]
The commit is actually signed off; I just did not add an additional "signed-off-by" to the PR comment. Then everything is fine, I hope :)

**Pull request merged**
