### PR TITLE
Ability to pause writing/reading of network state file for backups

### PR DESCRIPTION
**Pull request by triller-telekom**
Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by triller-telekom** [comment]
@cdjackson I would like to hear your opinion on this proposal.

This fix would make it possible to backup or restore the xml files while the coordinatorhandler keeps running, i..e. we do not need to dispose and re-initialize it.

Since this is only in the binding and only in the implementation and not in the interface, I think it doesn't harm anything.

**Comment by cdjackson** [comment]
I don't have any real problem with this. My only question is if it might be worth setting a flag if ```serialize``` is called when serialisation is paused, and then perform the serialisation when ```continueSerialization``` is called? It probably doesn't matter too much since the network is probably serialised regularly enough, but this might still be a good idea to ensure everything is consistent...

**Comment by triller-telekom** [comment]
> It probably doesn't matter too much since the network is probably serialised regularly enough

That was my assumption too.

But nevertheless I added that flag now. Since the `serialize` method needs the `Networkmanger` as a parameter, I am using this `Networkmanger` as a flag, i.e. if it is set, there was a call while paused and if it is `null` there was none.

If there was a call to `serialize` while paused, I am executing it once on resume.

Is this what you imagined?

**Comment by puzzle-star** [comment]
Hi @cdjackson and @triller-telekom,

If the purpose is to be able to backup the file, and the issue is that it cannot be done while it is being written because its contents would be partial, then the fix for issue #322 will solve this in a more straightaway fashion, as with it the file is atomically written, so it should be always on a backup-able state.

Pedro

**Comment by cdjackson** [comment]
@puzzle-star I don't think that #322 will resolve the issue here.  Let's assume for a second that the rename in #322 was an atomic operation (we can discuss that question in the other PR!) - since the copy (for the backup) required here is not, there will still be a problem.

Thread 1 - opens the file for backup and starts to read
Thread 2 - tries to rename the file

One of these two operations will fail - probably the copy/rename for the serialisation since I suspect that this will not work if the file is already open.

I know we are talking rare occasions here, but given that the power failure case you discuss in #322 should already be very rare, we trade one unlikely situation for another, but it doesn't actually solve anything.

**Comment by cdjackson** [comment]
@triller-telekom rethinking this - are you sure this is what you want to do? I thought from @hsudbrock that you were going to write a backup provider that was not simply copying this file, but actually interacted with the ```ZigBeeNetworkManager```. You should note that it is not possible to fully back / restore up the network using this file, and that is not its purpose (although it could probably be changed).

**Comment by puzzle-star** [comment]
Hi @cdjackson,

I tend to think of Linux/*nix...

Thanks case you describe above would work OK on Linux, as the rename is truly atomic, and removing a file is perfectly ok even if open (just the directory entry is removed, but the open fds still point to the right inode, which will persist till the file is closed by the las process)

But I will check on Windows

Also Java.nio.Files should provide platform independent way to for atomic moves / renamed (can it be usedcin the binding, or only Java.io.File?)

**Comment by cdjackson** [comment]
In some documentation I find on the web, I see 

> The renameTo() method returns boolean (true or false), indicating whether the renaming was successful. Renaming of moving a file may fail for various reasons, like the file being open, wrong file permissions etc.

I'm just wary that we probably can't guarantee this works on every system, with every JVM implementation.

**Comment by puzzle-star** [comment]
That's why I added the check, that deleted the file if the rename fails and then retries.

On OSes implementations where the the rename would fail, the reason is normally, even if I cannot imagine all scenarios, because if the target tfuke existing or being open (discarding permission issues, as the it would not work even now)

If java.nio.Files is an option, it should provide a platform independent way to do it. Will check later.

Keeping a trail of backups, as you say, would also work. Just take into account then that the file is updated quite often (I have seen > 30 updates in a couple of minutes, when the network is rediscovered).

**Comment by cdjackson** [comment]
> Keeping a trail of backups, as you say, would also work. Just take into account then that the file is updated quite often (I have seen > 30 updates in a couple of minutes, when the network is rediscovered).

Why does this matter?

**Comment by puzzle-star** [comment]
Because if we keep a limited number of backups (i.e. the last 5 ones), all of them will be in the last minute normally. If the purpose is to keep some history of backups, this won't do it. If not, just keeping the last one will do.

**Comment by cdjackson** [comment]
The purpose is not to keep a history - the purpose is to ensure reliability of data.

Can I suggest that we don't discuss this further here - it's not the right place. Thanks.

**Comment by puzzle-star** [comment]
Ok, then

**Comment by puzzle-star** [comment]
PS: which is the right place? :)

**Comment by cdjackson** [comment]
> PS: which is the right place? :)

Your PR - not this one. Your PR is looking at the strategy for serialisation which is what we are discussing, but it's not the right PR here.

**Comment by triller-telekom** [comment]
Alright, back to the topic :)

For sure i could serialize the network state within a backupprovider. But for this I need access to the coordinator to access its NetworkManager.

Yes, I need that access anyway for the trust center keys from the stick, but I would like to avoid it whereever possible. Also, for now its easier to just copy and restore the network file in case of a plain backup/restore without changing the usb stick.

So my question now is: Does it do any harm to the codebase if we allow for pausing and resuming the serialization? If not, I would like to see this PR merged.

What's your opinion on this?

**Comment by cdjackson** [comment]
No - I don't generally mind merging this, but on the other hand I would prefer not to add code if it doesn't actually do what is needed ;)

I'm in two minds though - you are having develop a backup provider, so why not just get access to the coordinator thing, which I think is not too hard (?? - I think Henning does it in the console already) and read out the state periodically? This is clearly a better solution as it allows you to generate all the data that you need - otherwise you will need to generate two backup solutions which seems a bit strange. I'm pretty sure that is what Henning was going to do when I discussed this with him a while back.

So - why not do that instead?

Again, I don't really mind merging this, but as I think this is only a Qivicon request as there is no plan in ESH or OH to have such a backup provider, I would prefer not to add code that no-one uses.

**Comment by cdjackson** [comment]
@triller-telekom and @hsudbrock do we still need this PR, or can Qivicon do the backup through other means? Henning - I recall we discussed this some time ago and you were going to directly access the ```ZigBeeNetworkManager``` to perform the backup/restore. Given that it is not possible to get all information you need from the XML, and will therefore have to implement another approach, doesn't it make sense to just have a single backup/restore rather than two different mechanisms?

**Comment by hsudbrock** [comment]
@cdjackson I am not sure about @triller-telekom 's status here - let's wait until he's back, then I can discuss with him.

**Comment by triller-telekom** [comment]
We do not need this PR anymore. I therefore close it.

**Pull request closed without merging**
