### PR TITLE
Use OHC serial transport

### PR DESCRIPTION
**Pull request by wborn**
Switches the binding to use the OHC serial transport instead of gnu.io directly.

Related to https://github.com/openhab/openhab-core/issues/1176

### CODE REVIEW

**Comment by cdjackson** [comment]
Yes, this does help to decouple the libraries, but at the moment this is not necessary and will require considerable work that I haven’t planned for. If we merge this, it’s just another thing that I need to do that will take my time and I’d therefore prefer not to do this now.

**Comment by wborn** [comment]
I will close this PR since I don't have time to babysit it and fix merge conflicts.

**Comment by kaikreuzer** [comment]
That's a pity, because I would have thought that we should now merge it for 3.x :-/

**Comment by wborn** [comment]
Yes but I don't get the impression there will be much progress in @cdjackson s repos for the foreseeable future.

**Comment by cdjackson** [comment]
> I don't get the impression there will be much progress in @cdjackson s repos for the foreseeable future.

I'm not sure why you think that?

**Comment by kaikreuzer** [comment]
> I would suggest to leave this open.

In order to merge it?

**Comment by cdjackson** [comment]
> In order to merge it?

Yes - I want to do a bunch of updates to get all the latest stuff merged over Christmas. This also includes updating to the latest ZigBee library (there is another PR open here for that) but I didn't want to merge all these changes prior to 2.5.

**Comment by wborn** [comment]
You can reopen it and merge it if you want. But make sure to do it before I cleanup stale branches in my fork.

**Comment by cdjackson** [comment]
Ok, but I won't be able to do anything for another week or so. As I said - this is a job for Christmas to get this and a number of other updates merged now that 2.5 is released.

**Comment by wborn** [comment]
OK great! The allow edits from maintainers checkbox is enabled. So it should be possible for them to fix any merge conflicts.

**Comment by wborn** [comment]
Thanks for merging it @cdjackson!

**Comment by cdjackson** [comment]
No probs - thanks for creating it :)

**Pull request merged**
