### PR TITLE
Add support for Sinope Line and Low Voltage Thermostats

### PR DESCRIPTION
**Pull request by WestCoastXS**
Static Definitions for Sinope TH1400ZB, TH1123ZB and TH1124ZB thermostats.

### CODE REVIEW

**Comment by WestCoastXS** [comment]
As discussed with @cdjackson on the openhab forum.

**Comment by cdjackson** [comment]
Thanks @WestCoastXS - this looks ok to me in general. I assume you've tested this, and the files look ok, but of course I can't test here.

Just 2 comments. 
* Can you run the formatter over the XML files please so they are nicely aligned.
* Can you sign one of the commits, and/or this PR - see the contributions file for how to do this (it's just a case of adding the "signed-off-by" statement)

**Comment by cdjackson** [comment]
@WestCoastXS I didn't spot that you have updated this PR - is it now ready as far as you are concerned? If so I'll do a last scan and hopefully get it merged.

**Comment by WestCoastXS** [comment]
Hi @cdjackson ,
No, I have not been able to get the channels for time and outside temperature going.
Haven't given up, just got busy with work.
Intending to get back to it soon.

I know there's a procedure to submit the PR, real name, etc, and will do that when I have it working.

**Pull request closed without merging**
